package mamali.qa.notify.utils.summerizer

val PERSIAN_STOP_WORDS = arrayOf(
    "و", "در", "به", "از", "که", "این", "را", "با", "است", "بر", "آن", "ها", "های", "برای",
    "شد", "ای", "تا", "یک", "بود", "نیز", "کرد", "می", "هم", "خود", "شود", "شده", "یا", "ما",
    "وی", "هر", "آنها", "شما", "او", "باید", "اگر", "پس", "کند", "کرده", "چون", "جز", "من",
    "اما", "تو", "آنان", "نمی", "نه", "بله", "دارد", "داشت", "چه", "چرا", "مگر", "باری", "هیچ",
    "همه", "جایی", "دیروز", "امروز", "هنوز", "همیشه", "هرگز", "آیا", "شاید", "کس", "کسی",
    "بسیار", "خیلی", "کم", "زیاد", "روی", "زیر", "توی", "بیرون", "درون", "تنها", "فقط",
    "اول", "دوم", "سوم", "چند", "چندین", "چیزی", "دیگر", "مرا", "ترا", "ما", "شما", "ایشان",
    "بودند", "بودم", "بودی", "است", "هستند", "هستم", "هستی", "نیست", "نیستند", "خواهند",
    "داشتند", "داشتم", "داشتی", "خواهم", "خواهی", "نخواهد", "می‌شود", "نمی‌شود", "می‌کند",
    "نمی‌کند", "خواهد", "شدن", "بودن", "کردن", "توانست", "توانستن", "گرفت", "دبرابر",
    "میان", "بین", "ضمن", "مورد", "جهت", "طریق", "چگونه", "چطور", "توسط", "باره"
)

val ENGLISH_STOP_WORDS =
    arrayOf(
        "i",
        "me",
        "my",
        "myself",
        "we",
        "our",
        "ours",
        "ourselves",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "he",
        "him",
        "his",
        "himself",
        "she",
        "her",
        "hers",
        "herself",
        "it",
        "its",
        "itself",
        "they",
        "them",
        "their",
        "theirs",
        "themselves",
        "what",
        "which",
        "who",
        "whom",
        "this",
        "that",
        "these",
        "those",
        "am",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "having",
        "do",
        "does",
        "did",
        "doing",
        "a",
        "an",
        "the",
        "and",
        "but",
        "if",
        "or",
        "because",
        "as",
        "until",
        "while",
        "of",
        "at",
        "by",
        "for",
        "with",
        "about",
        "against",
        "between",
        "into",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "to",
        "from",
        "up",
        "down",
        "in",
        "out",
        "on",
        "off",
        "over",
        "under",
        "again",
        "further",
        "then",
        "once",
        "here",
        "there",
        "when",
        "where",
        "why",
        "how",
        "all",
        "any",
        "both",
        "each",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "no",
        "nor",
        "not",
        "only",
        "own",
        "same",
        "so",
        "than",
        "too",
        "very",
        "s",
        "t",
        "can",
        "will",
        "just",
        "don",
        "should",
        "now",
    )